languageCode = "en-us"
title = "F5 experiences"
sectionPagesMenu = "main"
relativeURLs = true
googleAnalytics = "UA-177908951-1"
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "red"
author = "Sorin Boiangiu"
description = "F5 experiences"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]

name = "AWS_S3_deployment"

URL = "s3://f5experiences.com?region=eu-central-1"